routes:
  /rss/:
    template: rss
    content_type: text/xml

  /:
    template: landing

collections:
  /blog/:
    permalink: /blog/{slug}/
    template: index

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
