routes:
  /rss/:
    template: rss
    content_type: text/xml

  /:
    template: landing  # Página de inicio

  /test-prueba/:
    template: test_prueba  # Ruta para la nueva página

collections:
  /blog/:
    permalink: /blog/{slug}/
    template: index

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
